[workspace]
members = [
	"src/hyperlight_sandbox",
	"src/javascript_sandbox",
	"src/wasm_sandbox",
	"src/sdk/python/pyo3_common",
	"src/sdk/python/wasm_backend",
	"src/sdk/python/hyperlight_js_backend",
	"src/sdk/dotnet/ffi",
]
resolver = "2"

[workspace.package]
version = "0.6.0"
edition = "2024"
rust-version = "1.94"
license = "Apache-2.0"

[workspace.dependencies]
hyperlight-sandbox = { path = "src/hyperlight_sandbox" }
hyperlight-javascript-sandbox = { path = "src/javascript_sandbox" }
hyperlight-wasm-sandbox = { path = "src/wasm_sandbox" }
hyperlight-sandbox-pyo3-common = { path = "src/sdk/python/pyo3_common" }
hyperlight-common = { version = "0.17.0", default-features = false }
hyperlight-component-macro = "0.17.0"
hyperlight-host = { version = "0.17.0", default-features = false, features = ["executable_heap"] }
hyperlight-wasm = "0.15.0"
pyo3 = { version = "0.29", features = ["extension-module"] }
