repo-root := invocation_directory()
nanvix-rev := "f4bc205a40ed072cbb5f26b141498477985782f7"

build:
    cd {{repo-root}}/src/nanvix_sandbox && cargo +nightly build

setup-registry:
    @command -v hyperlight-nanvix >/dev/null 2>&1 || \
        cargo +nightly install --git https://github.com/hyperlight-dev/hyperlight-nanvix --rev {{nanvix-rev}}
    hyperlight-nanvix setup-registry

#### EXAMPLES ####

nanvix-sandbox-example: setup-registry
    cd {{repo-root}}/src/nanvix_sandbox && cargo +nightly run --example hello

examples: nanvix-sandbox-example
