[package]
name = "hyperlight-javascript-sandbox"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Hyperlight JS guest for hyperlight-sandbox"

[dependencies]
hyperlight-sandbox.workspace = true
anyhow = "1"
url = "2"
hyperlight-js = { git = "https://github.com/hyperlight-dev/hyperlight-js.git", rev = "b96774e7e19ce1945775498cd83d305a915e28df" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
